/*
 * JavaFX API 文檔
 * JavaFX 桌面應用後端 API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.swagger.client.JSON;

/**
 * 创建药品
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-17T20:51:51.230166200+08:00[Asia/Shanghai]", comments = "Generator version: 7.8.0")
public class CreateMedicineRequest {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  private String category;

  public static final String SERIALIZED_NAME_SPECIFICATION = "specification";
  @SerializedName(SERIALIZED_NAME_SPECIFICATION)
  private String specification;

  public static final String SERIALIZED_NAME_MANUFACTURER = "manufacturer";
  @SerializedName(SERIALIZED_NAME_MANUFACTURER)
  private String manufacturer;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private Double price;

  public static final String SERIALIZED_NAME_STOCK_QUANTITY = "stockQuantity";
  @SerializedName(SERIALIZED_NAME_STOCK_QUANTITY)
  private Integer stockQuantity;

  public static final String SERIALIZED_NAME_PRODUCTION_DATE = "productionDate";
  @SerializedName(SERIALIZED_NAME_PRODUCTION_DATE)
  private LocalDate productionDate;

  public static final String SERIALIZED_NAME_EXPIRY_DATE = "expiryDate";
  @SerializedName(SERIALIZED_NAME_EXPIRY_DATE)
  private LocalDate expiryDate;

  public static final String SERIALIZED_NAME_USAGE = "usage";
  @SerializedName(SERIALIZED_NAME_USAGE)
  private String usage;

  public static final String SERIALIZED_NAME_CONTRAINDICATION = "contraindication";
  @SerializedName(SERIALIZED_NAME_CONTRAINDICATION)
  private String contraindication;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public CreateMedicineRequest() {
  }

  public CreateMedicineRequest name(String name) {
    this.name = name;
    return this;
  }

  /**
   * 药品名称
   * @return name
   */
  @jakarta.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public CreateMedicineRequest category(String category) {
    this.category = category;
    return this;
  }

  /**
   * 类别
   * @return category
   */
  @jakarta.annotation.Nullable
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }


  public CreateMedicineRequest specification(String specification) {
    this.specification = specification;
    return this;
  }

  /**
   * 规格
   * @return specification
   */
  @jakarta.annotation.Nullable
  public String getSpecification() {
    return specification;
  }

  public void setSpecification(String specification) {
    this.specification = specification;
  }


  public CreateMedicineRequest manufacturer(String manufacturer) {
    this.manufacturer = manufacturer;
    return this;
  }

  /**
   * 生产厂商
   * @return manufacturer
   */
  @jakarta.annotation.Nullable
  public String getManufacturer() {
    return manufacturer;
  }

  public void setManufacturer(String manufacturer) {
    this.manufacturer = manufacturer;
  }


  public CreateMedicineRequest price(Double price) {
    this.price = price;
    return this;
  }

  /**
   * 价格
   * @return price
   */
  @jakarta.annotation.Nullable
  public Double getPrice() {
    return price;
  }

  public void setPrice(Double price) {
    this.price = price;
  }


  public CreateMedicineRequest stockQuantity(Integer stockQuantity) {
    this.stockQuantity = stockQuantity;
    return this;
  }

  /**
   * 库存数量
   * @return stockQuantity
   */
  @jakarta.annotation.Nullable
  public Integer getStockQuantity() {
    return stockQuantity;
  }

  public void setStockQuantity(Integer stockQuantity) {
    this.stockQuantity = stockQuantity;
  }


  public CreateMedicineRequest productionDate(LocalDate productionDate) {
    this.productionDate = productionDate;
    return this;
  }

  /**
   * 生产日期
   * @return productionDate
   */
  @jakarta.annotation.Nullable
  public LocalDate getProductionDate() {
    return productionDate;
  }

  public void setProductionDate(LocalDate productionDate) {
    this.productionDate = productionDate;
  }


  public CreateMedicineRequest expiryDate(LocalDate expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

  /**
   * 有效期至
   * @return expiryDate
   */
  @jakarta.annotation.Nullable
  public LocalDate getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(LocalDate expiryDate) {
    this.expiryDate = expiryDate;
  }


  public CreateMedicineRequest usage(String usage) {
    this.usage = usage;
    return this;
  }

  /**
   * 用法
   * @return usage
   */
  @jakarta.annotation.Nullable
  public String getUsage() {
    return usage;
  }

  public void setUsage(String usage) {
    this.usage = usage;
  }


  public CreateMedicineRequest contraindication(String contraindication) {
    this.contraindication = contraindication;
    return this;
  }

  /**
   * 禁忌症
   * @return contraindication
   */
  @jakarta.annotation.Nullable
  public String getContraindication() {
    return contraindication;
  }

  public void setContraindication(String contraindication) {
    this.contraindication = contraindication;
  }


  public CreateMedicineRequest status(String status) {
    this.status = status;
    return this;
  }

  /**
   * 状态
   * @return status
   */
  @jakarta.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateMedicineRequest createMedicineRequest = (CreateMedicineRequest) o;
    return Objects.equals(this.name, createMedicineRequest.name) &&
        Objects.equals(this.category, createMedicineRequest.category) &&
        Objects.equals(this.specification, createMedicineRequest.specification) &&
        Objects.equals(this.manufacturer, createMedicineRequest.manufacturer) &&
        Objects.equals(this.price, createMedicineRequest.price) &&
        Objects.equals(this.stockQuantity, createMedicineRequest.stockQuantity) &&
        Objects.equals(this.productionDate, createMedicineRequest.productionDate) &&
        Objects.equals(this.expiryDate, createMedicineRequest.expiryDate) &&
        Objects.equals(this.usage, createMedicineRequest.usage) &&
        Objects.equals(this.contraindication, createMedicineRequest.contraindication) &&
        Objects.equals(this.status, createMedicineRequest.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, category, specification, manufacturer, price, stockQuantity, productionDate, expiryDate, usage, contraindication, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateMedicineRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    specification: ").append(toIndentedString(specification)).append("\n");
    sb.append("    manufacturer: ").append(toIndentedString(manufacturer)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    stockQuantity: ").append(toIndentedString(stockQuantity)).append("\n");
    sb.append("    productionDate: ").append(toIndentedString(productionDate)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    usage: ").append(toIndentedString(usage)).append("\n");
    sb.append("    contraindication: ").append(toIndentedString(contraindication)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("category");
    openapiFields.add("specification");
    openapiFields.add("manufacturer");
    openapiFields.add("price");
    openapiFields.add("stockQuantity");
    openapiFields.add("productionDate");
    openapiFields.add("expiryDate");
    openapiFields.add("usage");
    openapiFields.add("contraindication");
    openapiFields.add("status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("name");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateMedicineRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateMedicineRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateMedicineRequest is not found in the empty JSON string", CreateMedicineRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateMedicineRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateMedicineRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateMedicineRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("category") != null && !jsonObj.get("category").isJsonNull()) && !jsonObj.get("category").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `category` to be a primitive type in the JSON string but got `%s`", jsonObj.get("category").toString()));
      }
      if ((jsonObj.get("specification") != null && !jsonObj.get("specification").isJsonNull()) && !jsonObj.get("specification").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `specification` to be a primitive type in the JSON string but got `%s`", jsonObj.get("specification").toString()));
      }
      if ((jsonObj.get("manufacturer") != null && !jsonObj.get("manufacturer").isJsonNull()) && !jsonObj.get("manufacturer").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `manufacturer` to be a primitive type in the JSON string but got `%s`", jsonObj.get("manufacturer").toString()));
      }
      if ((jsonObj.get("usage") != null && !jsonObj.get("usage").isJsonNull()) && !jsonObj.get("usage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `usage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("usage").toString()));
      }
      if ((jsonObj.get("contraindication") != null && !jsonObj.get("contraindication").isJsonNull()) && !jsonObj.get("contraindication").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `contraindication` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contraindication").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateMedicineRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateMedicineRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateMedicineRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateMedicineRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateMedicineRequest>() {
           @Override
           public void write(JsonWriter out, CreateMedicineRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateMedicineRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateMedicineRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateMedicineRequest
   * @throws IOException if the JSON string is invalid with respect to CreateMedicineRequest
   */
  public static CreateMedicineRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateMedicineRequest.class);
  }

  /**
   * Convert an instance of CreateMedicineRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

