/*
 * JavaFX API 文檔
 * JavaFX 桌面應用後端 API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.swagger.client.JSON;

/**
 * 返回數據
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-07T15:03:46.631816300+08:00[Asia/Taipei]", comments = "Generator version: 7.8.0")
public class InnerPhoneResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_ALBUM_ID = "albumId";
  @SerializedName(SERIALIZED_NAME_ALBUM_ID)
  private String albumId;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_THUMBNAIL_URL = "thumbnailUrl";
  @SerializedName(SERIALIZED_NAME_THUMBNAIL_URL)
  private String thumbnailUrl;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public InnerPhoneResponse() {
  }

  public InnerPhoneResponse id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * 
   * @return id
   */
  @jakarta.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public InnerPhoneResponse title(String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * 
   * @return title
   */
  @jakarta.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public InnerPhoneResponse albumId(String albumId) {
    this.albumId = albumId;
    return this;
  }

  /**
   * Get albumId
   * 
   * @return albumId
   */
  @jakarta.annotation.Nullable
  public String getAlbumId() {
    return albumId;
  }

  public void setAlbumId(String albumId) {
    this.albumId = albumId;
  }

  public InnerPhoneResponse url(String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * 
   * @return url
   */
  @jakarta.annotation.Nullable
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public InnerPhoneResponse thumbnailUrl(String thumbnailUrl) {
    this.thumbnailUrl = thumbnailUrl;
    return this;
  }

  /**
   * Get thumbnailUrl
   * 
   * @return thumbnailUrl
   */
  @jakarta.annotation.Nullable
  public String getThumbnailUrl() {
    return thumbnailUrl;
  }

  public void setThumbnailUrl(String thumbnailUrl) {
    this.thumbnailUrl = thumbnailUrl;
  }

  public InnerPhoneResponse createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * 
   * @return createdAt
   */
  @jakarta.annotation.Nullable
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InnerPhoneResponse innerPhoneResponse = (InnerPhoneResponse) o;
    return Objects.equals(this.id, innerPhoneResponse.id) &&
        Objects.equals(this.title, innerPhoneResponse.title) &&
        Objects.equals(this.albumId, innerPhoneResponse.albumId) &&
        Objects.equals(this.url, innerPhoneResponse.url) &&
        Objects.equals(this.thumbnailUrl, innerPhoneResponse.thumbnailUrl) &&
        Objects.equals(this.createdAt, innerPhoneResponse.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, title, albumId, url, thumbnailUrl, createdAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InnerPhoneResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    albumId: ").append(toIndentedString(albumId)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    thumbnailUrl: ").append(toIndentedString(thumbnailUrl)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("title");
    openapiFields.add("albumId");
    openapiFields.add("url");
    openapiFields.add("thumbnailUrl");
    openapiFields.add("createdAt");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to
   *                     InnerPhoneResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    if (jsonElement == null) {
      if (!InnerPhoneResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
        throw new IllegalArgumentException(
            String.format("The required field(s) %s in InnerPhoneResponse is not found in the empty JSON string",
                InnerPhoneResponse.openapiRequiredFields.toString()));
      }
    }

    Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
    // check to see if the JSON string contains additional fields
    for (Map.Entry<String, JsonElement> entry : entries) {
      if (!InnerPhoneResponse.openapiFields.contains(entry.getKey())) {
        throw new IllegalArgumentException(String.format(
            "The field `%s` in the JSON string is not defined in the `InnerPhoneResponse` properties. JSON: %s",
            entry.getKey(), jsonElement.toString()));
      }
    }
    JsonObject jsonObj = jsonElement.getAsJsonObject();
    if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("id").toString()));
    }
    if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull())
        && !jsonObj.get("title").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format("Expected the field `title` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("title").toString()));
    }
    if ((jsonObj.get("albumId") != null && !jsonObj.get("albumId").isJsonNull())
        && !jsonObj.get("albumId").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format("Expected the field `albumId` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("albumId").toString()));
    }
    if ((jsonObj.get("url") != null && !jsonObj.get("url").isJsonNull()) && !jsonObj.get("url").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("url").toString()));
    }
    if ((jsonObj.get("thumbnailUrl") != null && !jsonObj.get("thumbnailUrl").isJsonNull())
        && !jsonObj.get("thumbnailUrl").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format("Expected the field `thumbnailUrl` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("thumbnailUrl").toString()));
    }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
      if (!InnerPhoneResponse.class.isAssignableFrom(type.getRawType())) {
        return null; // this class only serializes 'InnerPhoneResponse' and its subtypes
      }
      final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
      final TypeAdapter<InnerPhoneResponse> thisAdapter = gson.getDelegateAdapter(this,
          TypeToken.get(InnerPhoneResponse.class));

      return (TypeAdapter<T>) new TypeAdapter<InnerPhoneResponse>() {
        @Override
        public void write(JsonWriter out, InnerPhoneResponse value) throws IOException {
          JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
          elementAdapter.write(out, obj);
        }

        @Override
        public InnerPhoneResponse read(JsonReader in) throws IOException {
          JsonElement jsonElement = elementAdapter.read(in);
          validateJsonElement(jsonElement);
          return thisAdapter.fromJsonTree(jsonElement);
        }

      }.nullSafe();
    }
  }

  /**
   * Create an instance of InnerPhoneResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of InnerPhoneResponse
   * @throws IOException if the JSON string is invalid with respect to
   *                     InnerPhoneResponse
   */
  public static InnerPhoneResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InnerPhoneResponse.class);
  }

  /**
   * Convert an instance of InnerPhoneResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
