/*
 * JavaFX API 文檔
 * JavaFX 桌面應用後端 API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.swagger.client.JSON;

/**
 * 返回數據
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-17T20:51:51.230166200+08:00[Asia/Shanghai]", comments = "Generator version: 7.8.0")
public class MedicalRecordInfoResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_PATIENT_ID = "patientId";
  @SerializedName(SERIALIZED_NAME_PATIENT_ID)
  private String patientId;

  public static final String SERIALIZED_NAME_PATIENT_NAME = "patientName";
  @SerializedName(SERIALIZED_NAME_PATIENT_NAME)
  private String patientName;

  public static final String SERIALIZED_NAME_DOCTOR_ID = "doctorId";
  @SerializedName(SERIALIZED_NAME_DOCTOR_ID)
  private String doctorId;

  public static final String SERIALIZED_NAME_DOCTOR_NAME = "doctorName";
  @SerializedName(SERIALIZED_NAME_DOCTOR_NAME)
  private String doctorName;

  public static final String SERIALIZED_NAME_DEPARTMENT = "department";
  @SerializedName(SERIALIZED_NAME_DEPARTMENT)
  private String department;

  public static final String SERIALIZED_NAME_VISIT_DATE = "visitDate";
  @SerializedName(SERIALIZED_NAME_VISIT_DATE)
  private LocalDate visitDate;

  public static final String SERIALIZED_NAME_CHIEF_COMPLAINT = "chiefComplaint";
  @SerializedName(SERIALIZED_NAME_CHIEF_COMPLAINT)
  private String chiefComplaint;

  public static final String SERIALIZED_NAME_DIAGNOSIS = "diagnosis";
  @SerializedName(SERIALIZED_NAME_DIAGNOSIS)
  private String diagnosis;

  public static final String SERIALIZED_NAME_TREATMENT_PLAN = "treatmentPlan";
  @SerializedName(SERIALIZED_NAME_TREATMENT_PLAN)
  private String treatmentPlan;

  public static final String SERIALIZED_NAME_PRESCRIPTIONS = "prescriptions";
  @SerializedName(SERIALIZED_NAME_PRESCRIPTIONS)
  private List<String> prescriptions = new ArrayList<>();

  public static final String SERIALIZED_NAME_EXAMINATION_RECORDS = "examinationRecords";
  @SerializedName(SERIALIZED_NAME_EXAMINATION_RECORDS)
  private List<String> examinationRecords = new ArrayList<>();

  public static final String SERIALIZED_NAME_NOTES = "notes";
  @SerializedName(SERIALIZED_NAME_NOTES)
  private String notes;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public MedicalRecordInfoResponse() {
  }

  public MedicalRecordInfoResponse id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  public MedicalRecordInfoResponse patientId(String patientId) {
    this.patientId = patientId;
    return this;
  }

  /**
   * Get patientId
   * @return patientId
   */
  @jakarta.annotation.Nullable
  public String getPatientId() {
    return patientId;
  }

  public void setPatientId(String patientId) {
    this.patientId = patientId;
  }


  public MedicalRecordInfoResponse patientName(String patientName) {
    this.patientName = patientName;
    return this;
  }

  /**
   * Get patientName
   * @return patientName
   */
  @jakarta.annotation.Nullable
  public String getPatientName() {
    return patientName;
  }

  public void setPatientName(String patientName) {
    this.patientName = patientName;
  }


  public MedicalRecordInfoResponse doctorId(String doctorId) {
    this.doctorId = doctorId;
    return this;
  }

  /**
   * Get doctorId
   * @return doctorId
   */
  @jakarta.annotation.Nullable
  public String getDoctorId() {
    return doctorId;
  }

  public void setDoctorId(String doctorId) {
    this.doctorId = doctorId;
  }


  public MedicalRecordInfoResponse doctorName(String doctorName) {
    this.doctorName = doctorName;
    return this;
  }

  /**
   * Get doctorName
   * @return doctorName
   */
  @jakarta.annotation.Nullable
  public String getDoctorName() {
    return doctorName;
  }

  public void setDoctorName(String doctorName) {
    this.doctorName = doctorName;
  }


  public MedicalRecordInfoResponse department(String department) {
    this.department = department;
    return this;
  }

  /**
   * Get department
   * @return department
   */
  @jakarta.annotation.Nullable
  public String getDepartment() {
    return department;
  }

  public void setDepartment(String department) {
    this.department = department;
  }


  public MedicalRecordInfoResponse visitDate(LocalDate visitDate) {
    this.visitDate = visitDate;
    return this;
  }

  /**
   * Get visitDate
   * @return visitDate
   */
  @jakarta.annotation.Nullable
  public LocalDate getVisitDate() {
    return visitDate;
  }

  public void setVisitDate(LocalDate visitDate) {
    this.visitDate = visitDate;
  }


  public MedicalRecordInfoResponse chiefComplaint(String chiefComplaint) {
    this.chiefComplaint = chiefComplaint;
    return this;
  }

  /**
   * Get chiefComplaint
   * @return chiefComplaint
   */
  @jakarta.annotation.Nullable
  public String getChiefComplaint() {
    return chiefComplaint;
  }

  public void setChiefComplaint(String chiefComplaint) {
    this.chiefComplaint = chiefComplaint;
  }


  public MedicalRecordInfoResponse diagnosis(String diagnosis) {
    this.diagnosis = diagnosis;
    return this;
  }

  /**
   * Get diagnosis
   * @return diagnosis
   */
  @jakarta.annotation.Nullable
  public String getDiagnosis() {
    return diagnosis;
  }

  public void setDiagnosis(String diagnosis) {
    this.diagnosis = diagnosis;
  }


  public MedicalRecordInfoResponse treatmentPlan(String treatmentPlan) {
    this.treatmentPlan = treatmentPlan;
    return this;
  }

  /**
   * Get treatmentPlan
   * @return treatmentPlan
   */
  @jakarta.annotation.Nullable
  public String getTreatmentPlan() {
    return treatmentPlan;
  }

  public void setTreatmentPlan(String treatmentPlan) {
    this.treatmentPlan = treatmentPlan;
  }


  public MedicalRecordInfoResponse prescriptions(List<String> prescriptions) {
    this.prescriptions = prescriptions;
    return this;
  }

  public MedicalRecordInfoResponse addPrescriptionsItem(String prescriptionsItem) {
    if (this.prescriptions == null) {
      this.prescriptions = new ArrayList<>();
    }
    this.prescriptions.add(prescriptionsItem);
    return this;
  }

  /**
   * Get prescriptions
   * @return prescriptions
   */
  @jakarta.annotation.Nullable
  public List<String> getPrescriptions() {
    return prescriptions;
  }

  public void setPrescriptions(List<String> prescriptions) {
    this.prescriptions = prescriptions;
  }


  public MedicalRecordInfoResponse examinationRecords(List<String> examinationRecords) {
    this.examinationRecords = examinationRecords;
    return this;
  }

  public MedicalRecordInfoResponse addExaminationRecordsItem(String examinationRecordsItem) {
    if (this.examinationRecords == null) {
      this.examinationRecords = new ArrayList<>();
    }
    this.examinationRecords.add(examinationRecordsItem);
    return this;
  }

  /**
   * Get examinationRecords
   * @return examinationRecords
   */
  @jakarta.annotation.Nullable
  public List<String> getExaminationRecords() {
    return examinationRecords;
  }

  public void setExaminationRecords(List<String> examinationRecords) {
    this.examinationRecords = examinationRecords;
  }


  public MedicalRecordInfoResponse notes(String notes) {
    this.notes = notes;
    return this;
  }

  /**
   * Get notes
   * @return notes
   */
  @jakarta.annotation.Nullable
  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }


  public MedicalRecordInfoResponse status(String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  public MedicalRecordInfoResponse createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MedicalRecordInfoResponse medicalRecordInfoResponse = (MedicalRecordInfoResponse) o;
    return Objects.equals(this.id, medicalRecordInfoResponse.id) &&
        Objects.equals(this.patientId, medicalRecordInfoResponse.patientId) &&
        Objects.equals(this.patientName, medicalRecordInfoResponse.patientName) &&
        Objects.equals(this.doctorId, medicalRecordInfoResponse.doctorId) &&
        Objects.equals(this.doctorName, medicalRecordInfoResponse.doctorName) &&
        Objects.equals(this.department, medicalRecordInfoResponse.department) &&
        Objects.equals(this.visitDate, medicalRecordInfoResponse.visitDate) &&
        Objects.equals(this.chiefComplaint, medicalRecordInfoResponse.chiefComplaint) &&
        Objects.equals(this.diagnosis, medicalRecordInfoResponse.diagnosis) &&
        Objects.equals(this.treatmentPlan, medicalRecordInfoResponse.treatmentPlan) &&
        Objects.equals(this.prescriptions, medicalRecordInfoResponse.prescriptions) &&
        Objects.equals(this.examinationRecords, medicalRecordInfoResponse.examinationRecords) &&
        Objects.equals(this.notes, medicalRecordInfoResponse.notes) &&
        Objects.equals(this.status, medicalRecordInfoResponse.status) &&
        Objects.equals(this.createdAt, medicalRecordInfoResponse.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, patientId, patientName, doctorId, doctorName, department, visitDate, chiefComplaint, diagnosis, treatmentPlan, prescriptions, examinationRecords, notes, status, createdAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MedicalRecordInfoResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    patientId: ").append(toIndentedString(patientId)).append("\n");
    sb.append("    patientName: ").append(toIndentedString(patientName)).append("\n");
    sb.append("    doctorId: ").append(toIndentedString(doctorId)).append("\n");
    sb.append("    doctorName: ").append(toIndentedString(doctorName)).append("\n");
    sb.append("    department: ").append(toIndentedString(department)).append("\n");
    sb.append("    visitDate: ").append(toIndentedString(visitDate)).append("\n");
    sb.append("    chiefComplaint: ").append(toIndentedString(chiefComplaint)).append("\n");
    sb.append("    diagnosis: ").append(toIndentedString(diagnosis)).append("\n");
    sb.append("    treatmentPlan: ").append(toIndentedString(treatmentPlan)).append("\n");
    sb.append("    prescriptions: ").append(toIndentedString(prescriptions)).append("\n");
    sb.append("    examinationRecords: ").append(toIndentedString(examinationRecords)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("patientId");
    openapiFields.add("patientName");
    openapiFields.add("doctorId");
    openapiFields.add("doctorName");
    openapiFields.add("department");
    openapiFields.add("visitDate");
    openapiFields.add("chiefComplaint");
    openapiFields.add("diagnosis");
    openapiFields.add("treatmentPlan");
    openapiFields.add("prescriptions");
    openapiFields.add("examinationRecords");
    openapiFields.add("notes");
    openapiFields.add("status");
    openapiFields.add("createdAt");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MedicalRecordInfoResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MedicalRecordInfoResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MedicalRecordInfoResponse is not found in the empty JSON string", MedicalRecordInfoResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MedicalRecordInfoResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MedicalRecordInfoResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("patientId") != null && !jsonObj.get("patientId").isJsonNull()) && !jsonObj.get("patientId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `patientId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("patientId").toString()));
      }
      if ((jsonObj.get("patientName") != null && !jsonObj.get("patientName").isJsonNull()) && !jsonObj.get("patientName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `patientName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("patientName").toString()));
      }
      if ((jsonObj.get("doctorId") != null && !jsonObj.get("doctorId").isJsonNull()) && !jsonObj.get("doctorId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `doctorId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("doctorId").toString()));
      }
      if ((jsonObj.get("doctorName") != null && !jsonObj.get("doctorName").isJsonNull()) && !jsonObj.get("doctorName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `doctorName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("doctorName").toString()));
      }
      if ((jsonObj.get("department") != null && !jsonObj.get("department").isJsonNull()) && !jsonObj.get("department").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `department` to be a primitive type in the JSON string but got `%s`", jsonObj.get("department").toString()));
      }
      if ((jsonObj.get("chiefComplaint") != null && !jsonObj.get("chiefComplaint").isJsonNull()) && !jsonObj.get("chiefComplaint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `chiefComplaint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("chiefComplaint").toString()));
      }
      if ((jsonObj.get("diagnosis") != null && !jsonObj.get("diagnosis").isJsonNull()) && !jsonObj.get("diagnosis").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `diagnosis` to be a primitive type in the JSON string but got `%s`", jsonObj.get("diagnosis").toString()));
      }
      if ((jsonObj.get("treatmentPlan") != null && !jsonObj.get("treatmentPlan").isJsonNull()) && !jsonObj.get("treatmentPlan").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `treatmentPlan` to be a primitive type in the JSON string but got `%s`", jsonObj.get("treatmentPlan").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("prescriptions") != null && !jsonObj.get("prescriptions").isJsonNull() && !jsonObj.get("prescriptions").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `prescriptions` to be an array in the JSON string but got `%s`", jsonObj.get("prescriptions").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("examinationRecords") != null && !jsonObj.get("examinationRecords").isJsonNull() && !jsonObj.get("examinationRecords").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `examinationRecords` to be an array in the JSON string but got `%s`", jsonObj.get("examinationRecords").toString()));
      }
      if ((jsonObj.get("notes") != null && !jsonObj.get("notes").isJsonNull()) && !jsonObj.get("notes").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `notes` to be a primitive type in the JSON string but got `%s`", jsonObj.get("notes").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MedicalRecordInfoResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MedicalRecordInfoResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MedicalRecordInfoResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MedicalRecordInfoResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<MedicalRecordInfoResponse>() {
           @Override
           public void write(JsonWriter out, MedicalRecordInfoResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MedicalRecordInfoResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MedicalRecordInfoResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MedicalRecordInfoResponse
   * @throws IOException if the JSON string is invalid with respect to MedicalRecordInfoResponse
   */
  public static MedicalRecordInfoResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MedicalRecordInfoResponse.class);
  }

  /**
   * Convert an instance of MedicalRecordInfoResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

