/*
 * JavaFX API 文檔
 * JavaFX 桌面應用後端 API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.swagger.client.JSON;

/**
 * 返回數據
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-17T20:51:51.230166200+08:00[Asia/Shanghai]", comments = "Generator version: 7.8.0")
public class PatientInfoResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_GENDER = "gender";
  @SerializedName(SERIALIZED_NAME_GENDER)
  private String gender;

  public static final String SERIALIZED_NAME_AGE = "age";
  @SerializedName(SERIALIZED_NAME_AGE)
  private Integer age;

  public static final String SERIALIZED_NAME_PHONE = "phone";
  @SerializedName(SERIALIZED_NAME_PHONE)
  private String phone;

  public static final String SERIALIZED_NAME_ID_CARD = "idCard";
  @SerializedName(SERIALIZED_NAME_ID_CARD)
  private String idCard;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private String address;

  public static final String SERIALIZED_NAME_EMERGENCY_CONTACT = "emergencyContact";
  @SerializedName(SERIALIZED_NAME_EMERGENCY_CONTACT)
  private String emergencyContact;

  public static final String SERIALIZED_NAME_EMERGENCY_PHONE = "emergencyPhone";
  @SerializedName(SERIALIZED_NAME_EMERGENCY_PHONE)
  private String emergencyPhone;

  public static final String SERIALIZED_NAME_REGISTRATION_DATE = "registrationDate";
  @SerializedName(SERIALIZED_NAME_REGISTRATION_DATE)
  private LocalDate registrationDate;

  public static final String SERIALIZED_NAME_MEDICAL_HISTORY = "medicalHistory";
  @SerializedName(SERIALIZED_NAME_MEDICAL_HISTORY)
  private List<String> medicalHistory = new ArrayList<>();

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public PatientInfoResponse() {
  }

  public PatientInfoResponse id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  public PatientInfoResponse name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public PatientInfoResponse gender(String gender) {
    this.gender = gender;
    return this;
  }

  /**
   * Get gender
   * @return gender
   */
  @jakarta.annotation.Nullable
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }


  public PatientInfoResponse age(Integer age) {
    this.age = age;
    return this;
  }

  /**
   * Get age
   * @return age
   */
  @jakarta.annotation.Nullable
  public Integer getAge() {
    return age;
  }

  public void setAge(Integer age) {
    this.age = age;
  }


  public PatientInfoResponse phone(String phone) {
    this.phone = phone;
    return this;
  }

  /**
   * Get phone
   * @return phone
   */
  @jakarta.annotation.Nullable
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }


  public PatientInfoResponse idCard(String idCard) {
    this.idCard = idCard;
    return this;
  }

  /**
   * Get idCard
   * @return idCard
   */
  @jakarta.annotation.Nullable
  public String getIdCard() {
    return idCard;
  }

  public void setIdCard(String idCard) {
    this.idCard = idCard;
  }


  public PatientInfoResponse address(String address) {
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @jakarta.annotation.Nullable
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }


  public PatientInfoResponse emergencyContact(String emergencyContact) {
    this.emergencyContact = emergencyContact;
    return this;
  }

  /**
   * Get emergencyContact
   * @return emergencyContact
   */
  @jakarta.annotation.Nullable
  public String getEmergencyContact() {
    return emergencyContact;
  }

  public void setEmergencyContact(String emergencyContact) {
    this.emergencyContact = emergencyContact;
  }


  public PatientInfoResponse emergencyPhone(String emergencyPhone) {
    this.emergencyPhone = emergencyPhone;
    return this;
  }

  /**
   * Get emergencyPhone
   * @return emergencyPhone
   */
  @jakarta.annotation.Nullable
  public String getEmergencyPhone() {
    return emergencyPhone;
  }

  public void setEmergencyPhone(String emergencyPhone) {
    this.emergencyPhone = emergencyPhone;
  }


  public PatientInfoResponse registrationDate(LocalDate registrationDate) {
    this.registrationDate = registrationDate;
    return this;
  }

  /**
   * Get registrationDate
   * @return registrationDate
   */
  @jakarta.annotation.Nullable
  public LocalDate getRegistrationDate() {
    return registrationDate;
  }

  public void setRegistrationDate(LocalDate registrationDate) {
    this.registrationDate = registrationDate;
  }


  public PatientInfoResponse medicalHistory(List<String> medicalHistory) {
    this.medicalHistory = medicalHistory;
    return this;
  }

  public PatientInfoResponse addMedicalHistoryItem(String medicalHistoryItem) {
    if (this.medicalHistory == null) {
      this.medicalHistory = new ArrayList<>();
    }
    this.medicalHistory.add(medicalHistoryItem);
    return this;
  }

  /**
   * Get medicalHistory
   * @return medicalHistory
   */
  @jakarta.annotation.Nullable
  public List<String> getMedicalHistory() {
    return medicalHistory;
  }

  public void setMedicalHistory(List<String> medicalHistory) {
    this.medicalHistory = medicalHistory;
  }


  public PatientInfoResponse status(String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PatientInfoResponse patientInfoResponse = (PatientInfoResponse) o;
    return Objects.equals(this.id, patientInfoResponse.id) &&
        Objects.equals(this.name, patientInfoResponse.name) &&
        Objects.equals(this.gender, patientInfoResponse.gender) &&
        Objects.equals(this.age, patientInfoResponse.age) &&
        Objects.equals(this.phone, patientInfoResponse.phone) &&
        Objects.equals(this.idCard, patientInfoResponse.idCard) &&
        Objects.equals(this.address, patientInfoResponse.address) &&
        Objects.equals(this.emergencyContact, patientInfoResponse.emergencyContact) &&
        Objects.equals(this.emergencyPhone, patientInfoResponse.emergencyPhone) &&
        Objects.equals(this.registrationDate, patientInfoResponse.registrationDate) &&
        Objects.equals(this.medicalHistory, patientInfoResponse.medicalHistory) &&
        Objects.equals(this.status, patientInfoResponse.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, gender, age, phone, idCard, address, emergencyContact, emergencyPhone, registrationDate, medicalHistory, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PatientInfoResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    age: ").append(toIndentedString(age)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    idCard: ").append(toIndentedString(idCard)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    emergencyContact: ").append(toIndentedString(emergencyContact)).append("\n");
    sb.append("    emergencyPhone: ").append(toIndentedString(emergencyPhone)).append("\n");
    sb.append("    registrationDate: ").append(toIndentedString(registrationDate)).append("\n");
    sb.append("    medicalHistory: ").append(toIndentedString(medicalHistory)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("name");
    openapiFields.add("gender");
    openapiFields.add("age");
    openapiFields.add("phone");
    openapiFields.add("idCard");
    openapiFields.add("address");
    openapiFields.add("emergencyContact");
    openapiFields.add("emergencyPhone");
    openapiFields.add("registrationDate");
    openapiFields.add("medicalHistory");
    openapiFields.add("status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PatientInfoResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PatientInfoResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PatientInfoResponse is not found in the empty JSON string", PatientInfoResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PatientInfoResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PatientInfoResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("gender") != null && !jsonObj.get("gender").isJsonNull()) && !jsonObj.get("gender").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `gender` to be a primitive type in the JSON string but got `%s`", jsonObj.get("gender").toString()));
      }
      if ((jsonObj.get("phone") != null && !jsonObj.get("phone").isJsonNull()) && !jsonObj.get("phone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `phone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("phone").toString()));
      }
      if ((jsonObj.get("idCard") != null && !jsonObj.get("idCard").isJsonNull()) && !jsonObj.get("idCard").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `idCard` to be a primitive type in the JSON string but got `%s`", jsonObj.get("idCard").toString()));
      }
      if ((jsonObj.get("address") != null && !jsonObj.get("address").isJsonNull()) && !jsonObj.get("address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("address").toString()));
      }
      if ((jsonObj.get("emergencyContact") != null && !jsonObj.get("emergencyContact").isJsonNull()) && !jsonObj.get("emergencyContact").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `emergencyContact` to be a primitive type in the JSON string but got `%s`", jsonObj.get("emergencyContact").toString()));
      }
      if ((jsonObj.get("emergencyPhone") != null && !jsonObj.get("emergencyPhone").isJsonNull()) && !jsonObj.get("emergencyPhone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `emergencyPhone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("emergencyPhone").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("medicalHistory") != null && !jsonObj.get("medicalHistory").isJsonNull() && !jsonObj.get("medicalHistory").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `medicalHistory` to be an array in the JSON string but got `%s`", jsonObj.get("medicalHistory").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PatientInfoResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PatientInfoResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PatientInfoResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PatientInfoResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<PatientInfoResponse>() {
           @Override
           public void write(JsonWriter out, PatientInfoResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PatientInfoResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PatientInfoResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PatientInfoResponse
   * @throws IOException if the JSON string is invalid with respect to PatientInfoResponse
   */
  public static PatientInfoResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PatientInfoResponse.class);
  }

  /**
   * Convert an instance of PatientInfoResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

