/*
 * JavaFX API 文檔
 * JavaFX 桌面應用後端 API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ModelLocalTime;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.swagger.client.JSON;

/**
 * 更新预约
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-17T20:51:51.230166200+08:00[Asia/Shanghai]", comments = "Generator version: 7.8.0")
public class UpdateAppointmentRequest {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_PATIENT_ID = "patientId";
  @SerializedName(SERIALIZED_NAME_PATIENT_ID)
  private String patientId;

  public static final String SERIALIZED_NAME_PATIENT_NAME = "patientName";
  @SerializedName(SERIALIZED_NAME_PATIENT_NAME)
  private String patientName;

  public static final String SERIALIZED_NAME_DOCTOR_ID = "doctorId";
  @SerializedName(SERIALIZED_NAME_DOCTOR_ID)
  private String doctorId;

  public static final String SERIALIZED_NAME_DOCTOR_NAME = "doctorName";
  @SerializedName(SERIALIZED_NAME_DOCTOR_NAME)
  private String doctorName;

  public static final String SERIALIZED_NAME_DEPARTMENT = "department";
  @SerializedName(SERIALIZED_NAME_DEPARTMENT)
  private String department;

  public static final String SERIALIZED_NAME_APPOINTMENT_DATE = "appointmentDate";
  @SerializedName(SERIALIZED_NAME_APPOINTMENT_DATE)
  private LocalDate appointmentDate;

  public static final String SERIALIZED_NAME_APPOINTMENT_TIME = "appointmentTime";
  @SerializedName(SERIALIZED_NAME_APPOINTMENT_TIME)
  private ModelLocalTime appointmentTime;

  public static final String SERIALIZED_NAME_APPOINTMENT_TYPE = "appointmentType";
  @SerializedName(SERIALIZED_NAME_APPOINTMENT_TYPE)
  private String appointmentType;

  public static final String SERIALIZED_NAME_SYMPTOMS = "symptoms";
  @SerializedName(SERIALIZED_NAME_SYMPTOMS)
  private String symptoms;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_NOTES = "notes";
  @SerializedName(SERIALIZED_NAME_NOTES)
  private String notes;

  public UpdateAppointmentRequest() {
  }

  public UpdateAppointmentRequest id(String id) {
    this.id = id;
    return this;
  }

  /**
   * 预约ID
   * @return id
   */
  @jakarta.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  public UpdateAppointmentRequest patientId(String patientId) {
    this.patientId = patientId;
    return this;
  }

  /**
   * 患者ID
   * @return patientId
   */
  @jakarta.annotation.Nullable
  public String getPatientId() {
    return patientId;
  }

  public void setPatientId(String patientId) {
    this.patientId = patientId;
  }


  public UpdateAppointmentRequest patientName(String patientName) {
    this.patientName = patientName;
    return this;
  }

  /**
   * 患者姓名
   * @return patientName
   */
  @jakarta.annotation.Nullable
  public String getPatientName() {
    return patientName;
  }

  public void setPatientName(String patientName) {
    this.patientName = patientName;
  }


  public UpdateAppointmentRequest doctorId(String doctorId) {
    this.doctorId = doctorId;
    return this;
  }

  /**
   * 医生ID
   * @return doctorId
   */
  @jakarta.annotation.Nullable
  public String getDoctorId() {
    return doctorId;
  }

  public void setDoctorId(String doctorId) {
    this.doctorId = doctorId;
  }


  public UpdateAppointmentRequest doctorName(String doctorName) {
    this.doctorName = doctorName;
    return this;
  }

  /**
   * 医生姓名
   * @return doctorName
   */
  @jakarta.annotation.Nullable
  public String getDoctorName() {
    return doctorName;
  }

  public void setDoctorName(String doctorName) {
    this.doctorName = doctorName;
  }


  public UpdateAppointmentRequest department(String department) {
    this.department = department;
    return this;
  }

  /**
   * 科室
   * @return department
   */
  @jakarta.annotation.Nullable
  public String getDepartment() {
    return department;
  }

  public void setDepartment(String department) {
    this.department = department;
  }


  public UpdateAppointmentRequest appointmentDate(LocalDate appointmentDate) {
    this.appointmentDate = appointmentDate;
    return this;
  }

  /**
   * 预约日期
   * @return appointmentDate
   */
  @jakarta.annotation.Nullable
  public LocalDate getAppointmentDate() {
    return appointmentDate;
  }

  public void setAppointmentDate(LocalDate appointmentDate) {
    this.appointmentDate = appointmentDate;
  }


  public UpdateAppointmentRequest appointmentTime(ModelLocalTime appointmentTime) {
    this.appointmentTime = appointmentTime;
    return this;
  }

  /**
   * Get appointmentTime
   * @return appointmentTime
   */
  @jakarta.annotation.Nullable
  public ModelLocalTime getAppointmentTime() {
    return appointmentTime;
  }

  public void setAppointmentTime(ModelLocalTime appointmentTime) {
    this.appointmentTime = appointmentTime;
  }


  public UpdateAppointmentRequest appointmentType(String appointmentType) {
    this.appointmentType = appointmentType;
    return this;
  }

  /**
   * 预约类型
   * @return appointmentType
   */
  @jakarta.annotation.Nullable
  public String getAppointmentType() {
    return appointmentType;
  }

  public void setAppointmentType(String appointmentType) {
    this.appointmentType = appointmentType;
  }


  public UpdateAppointmentRequest symptoms(String symptoms) {
    this.symptoms = symptoms;
    return this;
  }

  /**
   * 症状描述
   * @return symptoms
   */
  @jakarta.annotation.Nullable
  public String getSymptoms() {
    return symptoms;
  }

  public void setSymptoms(String symptoms) {
    this.symptoms = symptoms;
  }


  public UpdateAppointmentRequest status(String status) {
    this.status = status;
    return this;
  }

  /**
   * 状态
   * @return status
   */
  @jakarta.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  public UpdateAppointmentRequest notes(String notes) {
    this.notes = notes;
    return this;
  }

  /**
   * 备注
   * @return notes
   */
  @jakarta.annotation.Nullable
  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateAppointmentRequest updateAppointmentRequest = (UpdateAppointmentRequest) o;
    return Objects.equals(this.id, updateAppointmentRequest.id) &&
        Objects.equals(this.patientId, updateAppointmentRequest.patientId) &&
        Objects.equals(this.patientName, updateAppointmentRequest.patientName) &&
        Objects.equals(this.doctorId, updateAppointmentRequest.doctorId) &&
        Objects.equals(this.doctorName, updateAppointmentRequest.doctorName) &&
        Objects.equals(this.department, updateAppointmentRequest.department) &&
        Objects.equals(this.appointmentDate, updateAppointmentRequest.appointmentDate) &&
        Objects.equals(this.appointmentTime, updateAppointmentRequest.appointmentTime) &&
        Objects.equals(this.appointmentType, updateAppointmentRequest.appointmentType) &&
        Objects.equals(this.symptoms, updateAppointmentRequest.symptoms) &&
        Objects.equals(this.status, updateAppointmentRequest.status) &&
        Objects.equals(this.notes, updateAppointmentRequest.notes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, patientId, patientName, doctorId, doctorName, department, appointmentDate, appointmentTime, appointmentType, symptoms, status, notes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateAppointmentRequest {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    patientId: ").append(toIndentedString(patientId)).append("\n");
    sb.append("    patientName: ").append(toIndentedString(patientName)).append("\n");
    sb.append("    doctorId: ").append(toIndentedString(doctorId)).append("\n");
    sb.append("    doctorName: ").append(toIndentedString(doctorName)).append("\n");
    sb.append("    department: ").append(toIndentedString(department)).append("\n");
    sb.append("    appointmentDate: ").append(toIndentedString(appointmentDate)).append("\n");
    sb.append("    appointmentTime: ").append(toIndentedString(appointmentTime)).append("\n");
    sb.append("    appointmentType: ").append(toIndentedString(appointmentType)).append("\n");
    sb.append("    symptoms: ").append(toIndentedString(symptoms)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("patientId");
    openapiFields.add("patientName");
    openapiFields.add("doctorId");
    openapiFields.add("doctorName");
    openapiFields.add("department");
    openapiFields.add("appointmentDate");
    openapiFields.add("appointmentTime");
    openapiFields.add("appointmentType");
    openapiFields.add("symptoms");
    openapiFields.add("status");
    openapiFields.add("notes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateAppointmentRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateAppointmentRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateAppointmentRequest is not found in the empty JSON string", UpdateAppointmentRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateAppointmentRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UpdateAppointmentRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UpdateAppointmentRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("patientId") != null && !jsonObj.get("patientId").isJsonNull()) && !jsonObj.get("patientId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `patientId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("patientId").toString()));
      }
      if ((jsonObj.get("patientName") != null && !jsonObj.get("patientName").isJsonNull()) && !jsonObj.get("patientName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `patientName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("patientName").toString()));
      }
      if ((jsonObj.get("doctorId") != null && !jsonObj.get("doctorId").isJsonNull()) && !jsonObj.get("doctorId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `doctorId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("doctorId").toString()));
      }
      if ((jsonObj.get("doctorName") != null && !jsonObj.get("doctorName").isJsonNull()) && !jsonObj.get("doctorName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `doctorName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("doctorName").toString()));
      }
      if ((jsonObj.get("department") != null && !jsonObj.get("department").isJsonNull()) && !jsonObj.get("department").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `department` to be a primitive type in the JSON string but got `%s`", jsonObj.get("department").toString()));
      }
      // validate the optional field `appointmentTime`
      if (jsonObj.get("appointmentTime") != null && !jsonObj.get("appointmentTime").isJsonNull()) {
        ModelLocalTime.validateJsonElement(jsonObj.get("appointmentTime"));
      }
      if ((jsonObj.get("appointmentType") != null && !jsonObj.get("appointmentType").isJsonNull()) && !jsonObj.get("appointmentType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `appointmentType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("appointmentType").toString()));
      }
      if ((jsonObj.get("symptoms") != null && !jsonObj.get("symptoms").isJsonNull()) && !jsonObj.get("symptoms").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `symptoms` to be a primitive type in the JSON string but got `%s`", jsonObj.get("symptoms").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("notes") != null && !jsonObj.get("notes").isJsonNull()) && !jsonObj.get("notes").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `notes` to be a primitive type in the JSON string but got `%s`", jsonObj.get("notes").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateAppointmentRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateAppointmentRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateAppointmentRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateAppointmentRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateAppointmentRequest>() {
           @Override
           public void write(JsonWriter out, UpdateAppointmentRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateAppointmentRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateAppointmentRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateAppointmentRequest
   * @throws IOException if the JSON string is invalid with respect to UpdateAppointmentRequest
   */
  public static UpdateAppointmentRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateAppointmentRequest.class);
  }

  /**
   * Convert an instance of UpdateAppointmentRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

